development:
  adapter: mysql2
  encoding: utf8
  database: dashboard_newrelic
  host: localhost
  port: 3306
  username: vagrant
  password: vagrant

production:
  adapter: mysql2
  encoding: utf8
  database: dashboard_newrelic
  host: localhost
  port: 3306
  username: mysql
  password: mysql