development:
  adapter: mysql2
  database: dashboard_newrelic
  host: localhost
  pool: 5
  username: root
  password: vagrant

production:
  adapter: mysql2
  database: dashboard_newrelic
  host: localhost
  pool: 5
  username: mysql
  password: mysql